'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServicioDatos
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://localhost/", ConfigurationName:="ServicioDatos.ConexionAgendaSoap")>  _
    Public Interface ConexionAgendaSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/GetUsers", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetUsers(ByVal Nombre As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/GetUsers", ReplyAction:="*")>  _
        Function GetUsersAsync(ByVal Nombre As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ConexionAgendaSoapChannel
        Inherits ServicioDatos.ConexionAgendaSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ConexionAgendaSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServicioDatos.ConexionAgendaSoap)
        Implements ServicioDatos.ConexionAgendaSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetUsers(ByVal Nombre As String) As System.Data.DataSet Implements ServicioDatos.ConexionAgendaSoap.GetUsers
            Return MyBase.Channel.GetUsers(Nombre)
        End Function
        
        Public Function GetUsersAsync(ByVal Nombre As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServicioDatos.ConexionAgendaSoap.GetUsersAsync
            Return MyBase.Channel.GetUsersAsync(Nombre)
        End Function
    End Class
End Namespace
